### ISSUE TITLE
安装出错了

### ISSUE THREAD

**Issue by disburden** [msojocs/wechat-devtools-linux#1]
我执行./tool/setup-wechat-devtools 时出下下面这个错误
01-26 15:36:44.013  [ERROR] Error: Command[/home/disburden/install/wechat-devtools/tools/update-nwjs-node] not found
                                at resolveCommand (mew_util.js/task.js:489:23)                                                                                                          
                                at resolveCommandShebang (mew_util.js/task.js:527:39)                                                                                                   
                                at prepareExecution (mew_util.js/task.js:563:27)                                                                                                        
                                at executeCommand (mew_util.js/task.js:729:31)                                                                                                          
                                at Step.<anonymous> (/home/disburden/install/wechat-devtools/tools/setup-wechat-devtools:21:12)                                                         
                                at Function.Async.call (mew_util.js/async.js:678:39)                                                                                                    
                                at tryCall (mew_util.js/async.js:748:31)                                                                                                                
                                at tryCall (mew_util.js/async.js:53:17)                                                                                                                 
                                at Async.then (mew_util.js/async.js:747:21)                                                                                                             
                                at /home/disburden/install/wechat-devtools/tools/setup-wechat-devtools:13:4                                                                             
                                at Object.<anonymous> (/home/disburden/install/wechat-devtools/tools/setup-wechat-devtools:44:40)                                                       
                                at Module._compile (internal/modules/cjs/loader.js:753:30)                                                                                              
                                at Object.Module._extensions..js (internal/modules/cjs/loader.js:764:10)                                                                                
                                at Module.load (internal/modules/cjs/loader.js:663:32)                                                                                                  
                                at tryModuleLoad (internal/modules/cjs/loader.js:602:12)                                                                                                
                                at Function.Module._load (internal/modules/cjs/loader.js:594:3)                                                                                         
                                at Function.Module.runMain (internal/modules/cjs/loader.js:806:12)                                                                                      
                                at startup (internal/bootstrap/node.js:283:19)                                                                                                          
                                at bootstrapNodeJSCore (internal/bootstrap/node.js:812:3)

**Comment by jiyeme** [comment]
试试这个：`tools/setup-wechat-devtools-node`
结尾有个node

**Comment by disburden** [comment]
也试过了,一堆错误
npm ERR! code 1
npm ERR! path /home/disburden/install/wechat-devtools/package.nw/node_modules_tmp/node_modules/nodegit
npm ERR! command failed
npm ERR! command sh -c node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! [nodegit] Running pre-install script
npm ERR! [nodegit] Running install script
npm ERR! Failed to execute '/home/disburden/.config/nvm/versions/node/v17.0.1/bin/node /home/disburden/.config/nvm/versions/node/v17.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/disburden/install/wechat-devtools/package.nw/node_modules_tmp/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/disburden/install/wechat-devtools/package.nw/node_modules_tmp/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
npm ERR! node-pre-gyp
npm ERR! info it worked if it ends with ok
npm ERR! node-pre-gyp
npm ERR! info using node-pre-gyp@0.13.0
npm ERR! node-pre-gyp info using node@17.0.1 | linux | x64
npm ERR! node-pre-gyp
npm ERR! WARN Using request for node-pre-gyp https download
npm ERR! node-pre-gyp
npm ERR! info check checked for "/home/disburden/install/wechat-devtools/package.nw/node_modules_tmp/node_modules/nodegit/build/Release/nodegit.node" (not found)
npm ERR! node-pre-gyp
npm ERR! http GET https://npm.taobao.org/mirrors/nodegit/v0.27.0/nodegit-v0.27.0-node-v102-linux-x64.tar.gz
npm ERR! node-pre-gyp
npm ERR! http 404 https://npm.taobao.org/mirrors/nodegit/v0.27.0/nodegit-v0.27.0-node-v102-linux-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://npm.taobao.org/mirrors/nodegit/v0.27.0/nodegit-v0.27.0-node-v102-linux-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not found for nodegit@0.27.0 and node@17.0.1 (node-v102 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 404 status code downloading tarball https://npm.taobao.org/mirrors/nodegit/v0.27.0/nodegit-v0.27.0-node-v102-linux-x64.tar.gz
npm ERR! gyp
npm ERR! info
npm ERR! it worked if it ends with ok
npm ERR! gyp
npm ERR! info using node-gyp@8.2.0
npm ERR! gyp
npm ERR! info using
npm ERR! node@17.0.1 | linux | x64
npm ERR! gyp
npm ERR! info ok
npm ERR! gyp
npm ERR! 
npm ERR! info it worked if it ends with ok
npm ERR! gyp
npm ERR! info using node-gyp@8.2.0
npm ERR! gyp info using
npm ERR! node@17.0.1 | linux | x64
npm ERR! gyp
npm ERR! info
npm ERR! find Python using Python version 3.7.3 found at "/usr/bin/python3"
npm ERR! gyp
npm ERR! 
npm ERR! info
npm ERR! 
npm ERR! spawn
npm ERR! /usr/bin/python3
npm ERR! gyp
npm ERR! 
npm ERR! info
npm ERR! 
npm ERR! spawn args
npm ERR! [
npm ERR! gyp info spawn args   '/home/disburden/.config/nvm/versions/node/v17.0.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/disburden/install/wechat-devtools/package.nw/node_modules_tmp/node_modules/nodegit/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/disburden/.config/nvm/versions/node/v17.0.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/disburden/.cache/node-gyp/17.0.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/disburden/.cache/node-gyp/17.0.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/disburden/.config/nvm/versions/node/v17.0.1/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/disburden/.cache/node-gyp/17.0.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/disburden/install/wechat-devtools/package.nw/node_modules_tmp/node_modules/nodegit',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: 1: krb5-config: not found
npm ERR! gyp: Call to 'krb5-config gssapi --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp
npm ERR! ERR! configure error
npm ERR! gyp
npm ERR! ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/disburden/.config/nvm/versions/node/v17.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:353:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR!
npm ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp
npm ERR! ERR! System Linux 5.10.83-amd64-desktop
npm ERR! gyp ERR! command "/home/disburden/.config/nvm/versions/node/v17.0.1/bin/node" "/home/disburden/.config/nvm/versions/node/v17.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/disburden/install/wechat-devtools/package.nw/node_modules_tmp/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/home/disburden/install/wechat-devtools/package.nw/node_modules_tmp/node_modules/nodegit/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v102"
npm ERR! gyp
npm ERR! ERR! cwd /home/disburden/install/wechat-devtools/package.nw/node_modules_tmp/node_modules/nodegit
npm ERR! gyp ERR!
npm ERR! node -v v17.0.1
npm ERR! gyp ERR! node-gyp -v
npm ERR! v8.2.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp
npm ERR! ERR! build error
npm ERR! node-pre-gyp ERR!
npm ERR! stack Error: Failed to execute '/home/disburden/.config/nvm/versions/node/v17.0.1/bin/node /home/disburden/.config/nvm/versions/node/v17.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/disburden/install/wechat-devtools/package.nw/node_modules_tmp/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/disburden/install/wechat-devtools/package.nw/node_modules_tmp/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/disburden/install/wechat-devtools/package.nw/node_modules_tmp/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1062:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp
npm ERR! ERR! System Linux 5.10.83-amd64-desktop
npm ERR! node-pre-gyp ERR! command "/home/disburden/.config/nvm/versions/node/v17.0.1/bin/node" "/home/disburden/install/wechat-devtools/package.nw/node_modules_tmp/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp
npm ERR! ERR! cwd /home/disburden/install/wechat-devtools/package.nw/node_modules_tmp/node_modules/nodegit
npm ERR! node-pre-gyp ERR! node -v v17.0.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.13.0
npm ERR! node-pre-gyp ERR! not ok
npm ERR! [nodegit] ERROR - Could not finish install
npm ERR! [nodegit] ERROR - finished with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/disburden/.npm/_logs/2022-01-26T08_01_33_084Z-debug.log

**Comment by jiyeme** [comment]
这个是`node-gpy`的问题，我之前也遇到过;
这个问题有点难搞。
它跟`nodejs`、`python`版本有关。
奇怪，为什么`nodejs`版本不是目录自带的？
我试试看能不能尽量摆脱主机的`nodejs`。

**Comment by disburden** [comment]
感觉很复杂,要是能搞个完整的docker,是不是有可能可以一劳永逸?

**Comment by jiyeme** [comment]
理论上是可以的，借助docker进行安装，
安装完毕后删除docker,宿主可以直接用。
我试试看。

**Comment by jiyeme** [comment]
已支持docker并有release
